import { cache } from "react";
import {
	parseContentCollectionId,
	parseContentSeriesId,
	resolveContentClassification,
} from "../../domain/content/collection";
import { normalizeTalkId } from "../../domain/talk/id";
import type { Talk } from "../../domain/talk/types";
import talksJson from "../../generated/talks.json";

type SerializedTalk = Omit<
	Talk,
	| "recordedOnDate"
	| "slideLinks"
	| "kind"
	| "collectionId"
	| "collectionLabel"
	| "seriesId"
	| "seriesLabel"
> & {
	kind?: Talk["kind"];
	collectionId?: Talk["collectionId"];
	collectionLabel?: string;
	seriesId?: Talk["seriesId"];
	seriesLabel?: string;
	recordedOnDate: string | null;
	slideLinks?: string[];
};

function deserializeTalk(talk: SerializedTalk): Talk {
	const classification = resolveContentClassification({
		collectionSources: [talk.collectionLabel ?? "", talk.event],
		seriesSources: [talk.seriesLabel ?? ""],
	});

	return {
		...talk,
		kind: "talk",
		collectionId:
			parseContentCollectionId(talk.collectionId ?? "") ||
			classification.collectionId,
		collectionLabel: talk.collectionLabel ?? classification.collectionLabel,
		seriesId:
			parseContentSeriesId(talk.seriesId ?? "") || classification.seriesId,
		seriesLabel: talk.seriesLabel ?? classification.seriesLabel,
		recordedOnDate: talk.recordedOnDate ? new Date(talk.recordedOnDate) : null,
		slideLinks: talk.slideLinks ?? [],
		srtLink: talk.srtLink ?? null,
	};
}

const loadTalks = cache(async (): Promise<Talk[]> => {
	// SAFETY: talks.json is generated by generate-talks-json.ts from SerializedTalk values.
	return (talksJson as SerializedTalk[]).map(deserializeTalk);
});

const loadTalkIndex = cache(async (): Promise<Map<string, Talk>> => {
	const talks = await loadTalks();
	const index = new Map<string, Talk>();
	for (const talk of talks) {
		index.set(normalizeTalkId(talk.id), talk);
	}
	return index;
});

export async function getTalks(): Promise<Talk[]> {
	return loadTalks();
}

export async function getTalkById(id: string): Promise<Talk | null> {
	const index = await loadTalkIndex();
	return index.get(normalizeTalkId(id)) ?? null;
}
